variable "prefix" {
    description = "Prefix generated by the remote state (./deploy.sh)"
}
variable "resource_groups" {
    type = "map"
}


variable "location_map" {
    description = "Default location to create the resources"
    type = "map"
}

# Example:
# location_map = {
#     region1   = "southeastasia"
#     region2   = "eastasia"
# }

variable "security_center" {
    description = "Attributes: [contact_email,contact_phone]"
    type = "map"
}

variable "analytics_workspace_name" {
  
}